Components/login
zenitheesc/Zenith-Monitor pull request #68
Opened 2021-09-06 15:31 UTC by g-mafra

## What type of PR is this? (check all applicable)
- [ ] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Nesta branch foi desenvolvido o front-end da tela de login do usuário. Desenvolveu-se apenas a parte superficial da tela, se atentando aos detalhes na forma de preenchimento dos textos de entrada para efetuar o login.  A tela está representada pela figura abaixo:

![image](https://user-images.githubusercontent.com/81496731/132228720-bbe797ff-0024-44ba-8b83-a7dae43ad619.png)

# Testing

2021-09-08 18:16 UTC, VitorFCM commented
Na hora de escrever algo nas caixas de textos ocorreu um erro relativo a sobreposição de pixels. Esse é um erro comum nos inputs. Eu resolvi colocando um ``` CustomScrollView```  da seguinte forma:
```dart
Widget buildMainBody(BuildContext context) {
    return GridTile(
      child: CustomScrollView(
        slivers: [
          SliverFillRemaining(
            hasScrollBody: false,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Container(
                      width: MediaQuery.of(context).size.width * 0.07,
                    ),
                    Container(child: imageCircle(context)),
                  ],
                ),
                Container(
                  child: Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            loginContainersName(context, 'Nome', 'General'),
                            loginContainersName(
                                context, 'Sobrenome ', 'General')
                          ],
                        ),
                        loginContainersGeneral(context, 'Email ', 'General'),
                        loginContainersGeneral(context, 'Senha ', 'Password'),
                        loginContainersGeneral(
                            context, 'Confirmar senha ', 'Password'),
                      ],
                    ),
                  ),
                ),
                Container(
                  child: Container(
                    width: screenSize(context, "width", 1),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        smallContainer(context, 'Voltar', 0XFFE57373),
                        smallContainer(context, 'Submeter', 0XFF8BC34A)
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
```
![Screenshot_20210908-131750](https://user-images.githubusercontent.com/62776298/132561819-d5e23f93-4f18-49ac-85e1-fde3b8a26b3b.jpg)

2021-09-08 19:44 UTC, VitorFCM requested changes

2021-09-08 19:44 UTC, VitorFCM commented on lib/widgets/login.dart
> +    return GridTile(
Na hora de escrever algo nas caixas de textos ocorreu um erro relativo a sobreposição de pixels. Esse é um erro comum nos inputs.
![Screenshot_20210908-131750](https://user-images.githubusercontent.com/62776298/132561819-d5e23f93-4f18-49ac-85e1-fde3b8a26b3b.jpg)
 Eu resolvi colocando um ``` CustomScrollView```
```suggestion
    Widget buildMainBody(BuildContext context) {
    return GridTile(
      child: CustomScrollView(
        slivers: [
          SliverFillRemaining(
            hasScrollBody: false,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Container(
                      width: MediaQuery.of(context).size.width * 0.07,
                    ),
                    Container(child: imageCircle(context)),
                  ],
                ),
                Container(
                  child: Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            loginContainersName(context, 'Nome', 'General'),
                            loginContainersName(
                                context, 'Sobrenome ', 'General')
                          ],
                        ),
                        loginContainersGeneral(context, 'Email ', 'General'),
                        loginContainersGeneral(context, 'Senha ', 'Password'),
                        loginContainersGeneral(
                            context, 'Confirmar senha ', 'Password'),
                      ],
                    ),
                  ),
                ),
                Container(
                  child: Container(
                    width: screenSize(context, "width", 1),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        smallContainer(context, 'Voltar', 0XFFE57373),
                        smallContainer(context, 'Submeter', 0XFF8BC34A)
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
```

2021-09-08 20:38 UTC, VitorFCM requested changes

2021-09-08 20:38 UTC, VitorFCM commented on lib/widgets/login.dart
> +                    Image(image: AssetImage('assets/images/user_figure.png')))),
O ideal aqui é utilizar o ``` Icon ``` do flutter, utilizei o seguinte
```suggestion
                    Icon(
                Icons.person_outlined,
                size: userRadius * 0.65,
              ),
```

2021-09-08 20:38 UTC, VitorFCM commented on lib/widgets/login.dart
> +              image: AssetImage('assets/images/images_solid.png'),
Aqui é a mesma ideia do icone da pessoa. Porém, nós queremos que essa figura seja um botão para que o usuário busque a foto. Eu faria da seguinte forma
```suggestion
             IconButton(
                onPressed: () {},
                icon: Icon(
                  Icons.photo_library_outlined,
                  size: imageRadius * 0.5,
                ),
              ),
```
Fica faltando implementar a busca pela imagem na memória ou câmera do celular. Existem alguns pacotes do flutter para isso, por exemplo, o [image_picker](https://pub.dev/packages/image_picker)

2021-09-14 12:10 UTC, Franreno requested changes
Gostei das mudanças que vc fez mudando as imagens para os icones do próprio Flutter. 
Acho que agora só falta apagar as imagens antigas que não estão sendo mais utilizadas.

2021-09-16 01:46 UTC, g-mafra commented
> Gostei das mudanças que vc fez mudando as imagens para os icones do próprio Flutter.
> Acho que agora só falta apagar as imagens antigas que não estão sendo mais utilizadas.

Fiz isso agorinha e arrumei uns probleminhas que estavam rolando!

2021-09-16 21:28 UTC, Franreno approved these changes

2021-09-16 22:48 UTC, closed without merging